/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "add.h"

bool_t
xdr_Number (XDR *xdrs, Number *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_addargs (XDR *xdrs, addargs *objp)
{
	register int32_t *buf;

	 if (!xdr_Number (xdrs, &objp->i))
		 return FALSE;
	 if (!xdr_Number (xdrs, &objp->j))
		 return FALSE;
	return TRUE;
}
